apiVersion: apps/v1
kind: Deployment
  #namespace: linda
metadata:
  name: nginx-deployment-test2
  namespace: linda
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: linda-nginx2
        image: nginx:1.14.2
        ports:
        - containerPort: 80
